### PR TITLE
Modified endianness check to accomodate windows

### LINKED ISSUE #11: Endianness check fails on Windows
Endianness check fails on windows because of unavailability of endian.h file.

### PR DESCRIPTION
**Pull request by bhumitattarde**
Fixes #11

### CODE REVIEW

**Comment by bhumitattarde** [comment]
I don't have access to a windows machine so someone will have to test this before merging.

**Comment by knadh** [comment]
@rhnvrm @ajinasokan @ranjanrak Possible to test this on Windows? Otherwise, we'll leave this open until someone can test and confirm.

**Comment by rhnvrm** [comment]
Maybe, we can write the tests using github-actions and run them for windows venv.

`runs-on: windows-2019` 

https://github.com/actions/virtual-environments#available-environments

Also, here is the gitlab pipeline for reference for writing the ubuntu pipeline in github actions:

```yaml
build-job:
  image: debian:latest
  stage: build
  before_script:
    - apt update && apt -y install libssl-dev zlib1g-dev git g++ build-essential cmake googletest google-mock libgtest-dev libgmock-dev doxygen
    - git clone https://github.com/zerodha/cppkiteconnect.git
    - cd cppkiteconnect
    - cd deps && cmake .
    - cd deps && tar -xzvf uWebSocketsv-0.14.8.tar.gz && cd uWebSockets-0.14.8
    - make && make install
    - cd ../../../
  script:
    - cmake .
    - make docs
```

**Comment by bhumitattarde** [comment]
@knadh I tested this on windows. Feel free to merge.

**Review by knadh — APPROVED** [review]

**Pull request merged**
