### PR TITLE
refactor: fluent-ish interface for methods with lot of params

### PR DESCRIPTION
**Pull request by bhumitattarde**
- methods that used to take a lot of parameters have been refactored to take a single struct argument which has fluent-ish interface
- segregated response structs into separate files
- refactored method and struct names so they follow camel case
- other minor improvements like converting magic numbers to constants and using `DEFAULT*` constants as default values
- updated lint and format configs

### CODE REVIEW

**Review by rhnvrm — CHANGES_REQUESTED** [review]
I skimmed through the changes. It seems okay, could you update the GitHub workflow so that PRs to the v2 branch also run tests?

I think this will be the relevant line to change:

```
  pull_request:
    branches: [main]
```

Also, I think we should make tagged releases. Currently it will be difficult for users to figure out the changes etc. https://github.com/zerodha/cppkiteconnect/releases

**Comment by bhumitattarde** [comment]
> I skimmed through the changes. It seems okay, could you update the GitHub workflow so that PRs to the v2 branch also run tests?

#46

> Also, I think we should make tagged releases. Currently it will be difficult for users to figure out the changes etc. https://github.com/zerodha/cppkiteconnect/releases

I was planning to do this once v2 is ready. Current `main` would have been `1.0.0`, `main` once `v2` is ready would have been `2.0.0` and then semantic versioning for further releases. Would you like me to make alpha releases from now itself?

**Comment by rhnvrm** [comment]
Merged #46; although I can't see the pipeline checks

> I was planning to do this once v2 is ready. Current main would have been 1.0.0, main once v2 is ready and merged would have been 2.0.0 and then semantic versioning for further releases. Would you like me to make alpha releases from now itself?

Let's tag and release the current main branch as v1.0.0 before merging itself; I guess we missed creating releases earlier. About the future releases, once we merge this we can tag that as v2.

**Review by rhnvrm — APPROVED** [review]

**Comment by bhumitattarde** [comment]
I'll force push without any changes later. That should trigger the workflows.

**Pull request merged**
