### PR TITLE
feat: basket margin endpoint

### LINKED ISSUE #66: Basket Margin Support
Can we have support for getting Basket order margin for C++ API? (https://kite.trade/docs/connect/v3/margins/#basket-margins)

### PR DESCRIPTION
**Pull request by bhumitattarde**
Test once please. Closes #66.

@rhnvrm You'll need to run docs pipeline once this is merged.

### CODE REVIEW

**Comment by navkamalrakra** [comment]
Hi, can we have this merged if possible ?

**Comment by bhumitattarde** [comment]
> Hi, can we have this merged if possible ?

@rhnvrm

**Comment by rhnvrm** [comment]
Looks okay. @ranjanrak possible to run and check once?

**Comment by navkamalrakra** [comment]
Gentle reminder to look at it.

**Review by ranjanrak — APPROVED** [review]

**Comment by ranjanrak** [comment]
Checked. Looks fine :+1:

**Comment by bhumitattarde** [comment]
Will need @rhnvrm / @knadh to approve for merging.

**Review by rhnvrm — APPROVED** [review]

**Comment by rhnvrm** [comment]
Docs are updated

https://kite.trade/docs/cppkiteconnect/classkiteconnect_1_1kite.html#ae519979bc455eea069b8dd306c5ee831

**Pull request merged**
